### PR TITLE
chore(Creature): improved several tooltips

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
### CREATURE.TEMPLATE
In: "difficulty_entry_3": "Entry of the equivalent creature in 25man Heroic Raid",

Corrected `difficulty_entry_3` to `DIFFICULTY_ENTRY_3` to match the others.

Created: 
`ITEMID1`: "This is the item number of the equipment used in the right hand from Item.dbc.",
`ITEMID2`: "This is the item number of the equipment used in the left hand from Item.dbc.",
`ITEMID3`: "This is the item number of the equipment used in the ranged slot from Item.dbc."

### ~CREATURE.TEMPLATE_RESISTANCE~

~Created:~

~TEMPLATE_RESISTANCE.SCHOOL: `1 - SPELL_SCHOOL_HOLY; 2 - SPELL_SCHOOL_FIRE; 3 - SPELL_SCHOOL_NATURE; 4 - SPELL_SCHOOL_FROST; 5 - SPELL_SCHOOL_SHADOW; 6 - SPELL_SCHOOL_ARCANE`~

### creature_equip_template

Added `[tooltip]="'UNIQUE_ID' | translate: { ENTITY: 'creature' }` to creatureID to match the others Infos for the CreatureID

Created: 
`[tooltip]="'CREATURE.TEMPLATE.ITEMID1' | translate`
`[tooltip]="'CREATURE.TEMPLATE.ITEMID2' | translate`
`[tooltip]="'CREATURE.TEMPLATE.ITEMID3' | translate`

For each respective itemID.

### creature_onkill_reputation

Added `[tooltip]="'UNIQUE_ID' | translate: { ENTITY: 'creature' }` to creatureID to match the others Infos for the CreatureID

### ~creature_template_resistance~

~Created:~

~`[tooltip]="'CREATURE.TEMPLATE_RESISTANCE.SCHOOL' | translate`~

---

Resovles: https://github.com/azerothcore/Keira3/issues/3122

### CODE REVIEW

**Comment by TheSCREWEDSoftware** [comment]
I don't know how to test these in my local machine, I'm aware it's a webpage type of thing. I followed the trace how things were called and made and i think I did alright

**Comment by FrancescoBorzi** [comment]
@TheSCREWEDSoftware thanks for contributing!

> I don't know how to test these in my local machine

Please follow https://github.com/azerothcore/Keira3?tab=readme-ov-file#how-to-run-keira3-in-development-mode

Feel free to ping us on Discord if you need any help!

**Comment by TheSCREWEDSoftware** [comment]
<details>
<summary>Images </summary>

Onkill Rep 
image

Equip 

image

image

image

image

Resistance (waiting feeedback) needs better formating if not needing to be reverted

image


</details>

**Comment by Helias** [comment]
About the school field we could improve it putting a selector, I can do it in another PR maybe ;-)

**Comment by TheSCREWEDSoftware** [comment]
@FrancescoBorzi I've reverted the tooltip changes for the School in Template Resistance. All is working as intended.

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
