### PR TITLE
chore(Condition/ConditionValue2): fix tooltip for CONDITION_QUESTSTATE 

### PR DESCRIPTION
**Pull request by Kitzunu**

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Kitzunu shall we create a flag selector for this?

**Comment by Kitzunu** [comment]
Honestly that could be neat for everything that has fixed flags

**Comment by Kitzunu** [comment]
If you do the first / show me how it works then I can look into it

**Comment by FrancescoBorzi** [comment]
@Kitzunu sure thing!

**Comment by FrancescoBorzi** [comment]
Closing in favour of:

https://github.com/azerothcore/Keira3/pull/702

**Pull request closed without merging**
