### PR TITLE
Add missing SmartScript stuff.

### PR DESCRIPTION
**Pull request by avarishd**
https://github.com/azerothcore/Keira3/issues/1607
And correct sound and sound random.

### CODE REVIEW

**Comment by avarishd** [comment]
I assume the build is failing because of stuff not being up to date in the repository?

**Comment by Helias** [comment]
I strongly appreciate your effort on this, hope to help you with any issues
are you able to run your Keira3 version locally right?

**Comment by Helias** [comment]
> I assume the build is failing because of stuff not being up to date in the repository?

I read it only now, yeah I think it depends on some package versions, it does not depends on you

**Comment by Helias** [comment]
you could try to run "npm install" and push the package-lock file

**Comment by avarishd** [comment]
Can't, it's in .gitignore 😄

**Comment by Helias** [comment]
`package-lock.json` it's not in `.gitignore` , it's only in `.prettierignore`, try to push it in your branch

**Comment by avarishd** [comment]
Can't, no changes there.

**Comment by Helias** [comment]
the issues seems related to the tests, we have to fix them

**Review by Helias — APPROVED** [review]

**Comment by avarishd** [comment]
Keep https://github.com/azerothcore/Keira3/issues/1607 open, to be used as comment generation guidelines.

**Pull request merged**
