### PR TITLE
feat(creature_template): spell_school_immune_mask

### PR DESCRIPTION
**Pull request by Kitzunu**
closes https://github.com/azerothcore/Keira3/issues/1074

### CODE REVIEW

**Comment by Kitzunu** [comment]
image
image
image
image

**Comment by FrancescoBorzi** [comment]
@Kitzunu looks good overall, but the tests are failing

**Comment by Kitzunu** [comment]
I dont understand the errors, there are like a million errors unrelated to the PR

**Comment by FrancescoBorzi** [comment]
@Kitzunu it's just a test case that is failing because the expected SQL query does not match with the actual SQL query. Which is normal as you added an extra field. So it's just a matter of putting the correct expected query. I can help with it later if needed.

**Comment by Kitzunu** [comment]
nice

**Review by Helias — APPROVED** [review]

**Pull request merged**
