### PR TITLE
feat(main.ts): Add Keira3 navigation bar

### PR DESCRIPTION
**Pull request by Kitzunu**
Builds

Tested on Windows and all works as it should :) 

closes https://github.com/azerothcore/Keira3/issues/658

### CODE REVIEW

**Comment by Kitzunu** [comment]
closes https://github.com/azerothcore/Keira3/issues/658

**Comment by FrancescoBorzi** [comment]
@Kitzunu does this preserve all the current keyboard shortcuts, e.g. opening dev tools with `ctrl`+`alt`+`i` etc.. ?

**Comment by Kitzunu** [comment]
Yes, electron has built in role: '' that has all the shortcuts

**Comment by Kitzunu** [comment]
You can also create own shortcuts for "custom" options, like the redirect to repo

**Comment by Helias** [comment]
this question is a bit off-topic, but, is there a way to add the functionality to search in the page, like using "Ctrl+F" in the browser?

**Comment by Kitzunu** [comment]
@Helias good question... I think that would need to be "custom" implementation because Electron don't have a predefined role for it https://www.electronjs.org/docs/api/menu-item#roles

**Comment by Kitzunu** [comment]
@Helias https://github.com/TheoXiong/electron-find

**Comment by Helias** [comment]
very nice, thank you

**Comment by Kitzunu** [comment]
I really can't understand this https://app.codacy.com/manual/FrancescoBorzi/Keira3/pullRequest?prid=5845722 it is equal to all other click functions

**Comment by FrancescoBorzi** [comment]
Tested on mac, everything works as expected

**Comment by Kitzunu** [comment]
Weird tyhat Codacy didnt say it here https://github.com/azerothcore/Keira3/pull/792/commits/3628f4de29cc8f0ee20d293233cf10e32b8e4ed5

**Pull request merged**
