### PR TITLE
add detection_range to modifiers

### PR DESCRIPTION
**Pull request by Krejza9**
Add detection_range to modifiers
Close: #1373

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Krejza9 thanks for this PR. Unfortuantely there is still a broken test, can you please fix it? If you need any assistance, just pke me

**Comment by Krejza9** [comment]
I think I found where the problem is, the tests don't count the new column in the DB, I rewrite them

**Comment by Krejza9** [comment]
To be honest, I don't understand why the test is failing.
image

I've got it right there
image
and he skips it like the value isn't even there.

**Comment by Helias** [comment]
I'll have a look

**Comment by Helias** [comment]
the number "20" is auto-generated from `changeAllFields()`, but if you set it as the default value of detection_range it will not trigger the "change" in the unit-test because it is already 20 as value.
I set "1" as the default value because in the DB 1 is the default value and changed the unit-test.

Now it should be ok

**Comment by Krejza9** [comment]
I see, thanks for the explanation and correction.

**Pull request merged**
