### PR TITLE
[Needs testing] feat: Bootstrap 5

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
https://getbootstrap.com/docs/5.0/migration/

- Closes https://github.com/azerothcore/Keira3/issues/1249

**NEEDS TESTING**

Please test this PR [by running Keira3 in development mode](https://github.com/azerothcore/Keira3#how-to-run-keira3-in-development-mode) and checking out this branch using `git checkout bootstrap-5`

Have a look around the app and report any layout issues.

### CODE REVIEW

**Comment by anguaive** [comment]
All I could find from my cursory look was a couple of missing margins:

Between buttons in `keira-editor-buttons`:


Between the input and the button on the 'Create new' panel:


Between labels and other elements above the editor input fields:

**Comment by FrancescoBorzi** [comment]
@anguaive thanks a lot for testing! I'll have another look at it

**Comment by FrancescoBorzi** [comment]
@anguaive it is strange because actually those bugs you mentioned were already fixed in this PR, I cannot reproduce them anymore. Are you sure you're using the latest version of this PR?

image

image

**Comment by anguaive** [comment]
@FrancescoBorzi Nope. I guess I was being dumb as usual and forgot to rebuild after checking out the new branch :D The stuff I found is indeed fixed already.

**Comment by FrancescoBorzi** [comment]
@anguaive no problem and thank you very much! 4 eyes are better than 2, I think this is safe to merge

**Pull request merged**
