### PR TITLE
chore(SAI/Target): implement PLAYER_WITH_AURA

### PR DESCRIPTION
**Pull request by Kitzunu**
part of https://github.com/azerothcore/azerothcore-wotlk/pull/2879

TODO: Add generated comment.
(I don't understand how it works for target)

### CODE REVIEW

**Comment by P-Kito** [comment]
This is not random point, this is smart target player with aura x)

**Comment by Kitzunu** [comment]
Oh I named it wrong xD

**Comment by FrancescoBorzi** [comment]
@Kitzunu what part you don't understand exactly? I can explain

**Comment by Kitzunu** [comment]
The auto comment for target is different from action and event, I dont understand how that file works.

**Comment by FrancescoBorzi** [comment]
@Kitzunu I'll open a new PR to finish this

**Pull request merged**
