### PR TITLE
feat: release Linux deb file

### PR DESCRIPTION
**Pull request by FrancescoBorzi**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
deb + appimage? awesome xD

**Comment by FrancescoBorzi** [comment]
yes, we can release any of the following:

image

https://www.electron.build/configuration/linux

not sure which other formats make sense to release, apart from `deb` and maybe `rpm`

**Comment by BarbzYHOOL** [comment]
well let's wait until someone asks for another format

**Comment by FrancescoBorzi** [comment]
I discussed with Helias and we decided to go with: deb, rpm, snap & AppImage (https://github.com/azerothcore/Keira3/pull/58) then we will add more if needed

**Pull request merged**
